/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Message { 'text' : string, 'sender' : string }
export interface Profile {
  'username' : string,
  'coins' : bigint,
  'lastDailyReward' : bigint,
  'isVIP' : boolean,
}
export interface _SERVICE {
  'claimDailyReward' : ActorMethod<[bigint], undefined>,
  'getMessages' : ActorMethod<[], Array<Message>>,
  'getProfile' : ActorMethod<[], Profile>,
  'playBlackjack' : ActorMethod<[bigint, boolean], undefined>,
  'playCardFlip' : ActorMethod<[bigint], undefined>,
  'playDice' : ActorMethod<[bigint, boolean], undefined>,
  'playSlots' : ActorMethod<[bigint, bigint], undefined>,
  'purchaseVIP' : ActorMethod<[], undefined>,
  'registerUser' : ActorMethod<[string], undefined>,
  'sendMessage' : ActorMethod<[string], undefined>,
  'spinWheel' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];