/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Message = IDL.Record({ 'text' : IDL.Text, 'sender' : IDL.Text });
export const Profile = IDL.Record({
  'username' : IDL.Text,
  'coins' : IDL.Nat,
  'lastDailyReward' : IDL.Int,
  'isVIP' : IDL.Bool,
});

export const idlService = IDL.Service({
  'claimDailyReward' : IDL.Func([IDL.Nat], [], []),
  'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getProfile' : IDL.Func([], [Profile], ['query']),
  'playBlackjack' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'playCardFlip' : IDL.Func([IDL.Nat], [], []),
  'playDice' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'playSlots' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'purchaseVIP' : IDL.Func([], [], []),
  'registerUser' : IDL.Func([IDL.Text], [], []),
  'sendMessage' : IDL.Func([IDL.Text], [], []),
  'spinWheel' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Message = IDL.Record({ 'text' : IDL.Text, 'sender' : IDL.Text });
  const Profile = IDL.Record({
    'username' : IDL.Text,
    'coins' : IDL.Nat,
    'lastDailyReward' : IDL.Int,
    'isVIP' : IDL.Bool,
  });
  
  return IDL.Service({
    'claimDailyReward' : IDL.Func([IDL.Nat], [], []),
    'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getProfile' : IDL.Func([], [Profile], ['query']),
    'playBlackjack' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'playCardFlip' : IDL.Func([IDL.Nat], [], []),
    'playDice' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'playSlots' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'purchaseVIP' : IDL.Func([], [], []),
    'registerUser' : IDL.Func([IDL.Text], [], []),
    'sendMessage' : IDL.Func([IDL.Text], [], []),
    'spinWheel' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };